### ISSUE TITLE
Unsupported operand types: int - string

### ISSUE THREAD

**Issue by allurco** [vinkla/laravel-hashids#151]
Hi, 

I am using the package with Laravel 9 in a PHP 8 environment. I am getting the following error in Hashid.php line 203:

`Unsupported operand types: int - string
`

Here is the stack trace: https://flareapp.io/share/VmeLXOq5#F77

Is this related with an incompatibility with php 8? 

Best

**Comment by vinkla** [comment]
@allurco please submit a pull request with failing tests.

**Comment by pmochine** [comment]
@vinkla Here I made a simple test where it's failing. Please have a look: https://github.com/pmochine/hashid-test

**Comment by pmochine** [comment]
Ahh ok, I found the issue @vinkla

It's this line `$excess = \mb_strlen($ret) - $this->minHashLength;``

In PHP 7.4 this was not an issue, but with PHP 8 being stricter you cannot subtract a value from a string.

The issue is that in my case that the default length is set to `'length' => 'your-length-integer',`. 

If you are developing a package, you have to set the length manually in your `TestCase.php`.

For example in your `TestCase.php`

     /**
     * Define environment setup.
     * https://packages.tools/testbench/basic/define-environment.html#using-annotation
     *
     * @param  \Illuminate\Foundation\Application   $app
     *
     * @return void
     */
    protected function getEnvironmentSetUp($app)
    {
        $app['config']->set('hashids.connections.main.length', 10);
    }

I hope it helps :)

**Comment by vinkla** [comment]
Thanks for looking into it @pmochine! I think the easiest way forward is to set the default length to 0 in the configuration file. Since you found the issue, would you be up to send a pull request?
