### ISSUE TITLE
setting up custom salt or custom parameters

### ISSUE THREAD

**Issue by dingman** [vinkla/laravel-hashids#65]
Where would I setup my custom salt or custom parameters that I want to use as default, such as minimum length?
Thanks!

**Comment by vinkla** [comment]
In the configuration file: https://github.com/vinkla/laravel-hashids/blob/052ee165751cb4dfcd2801d234e9e5835a1c0d56/config/hashids.php#L42-L45

**Comment by dingman** [comment]
Great, thanks.

When I ran composer, it didn't install this file. Would be great if you could update your package to include this and show some documentation for others. Cheers! Great work on this package.

**Comment by vinkla** [comment]
This is already in the documentation. Did you follow it?

**Comment by dingman** [comment]
yes I did. That file was not created, I had to create it myself. Don't know why. I added the file and everything works as expected now.

**Comment by vinkla** [comment]
TBH I’m tired if people being passive aggressive on GitHub. Your comment on updating the package and the documentation wasn’t nice IMO. This package has been downloaded over 300k times. If the package or docs were be a problem it would already have been fixed by now. This issue is most probably something on your end.  Please do some research in the future.

**Comment by dingman** [comment]
Well, my notes were not intended to be harmful in any way. I hope your day improves.

Thank you for your help.
